version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    container_name: invillia_app
    ports:
      - 8080:80
    volumes:
      - ./:/data/invillia_app
      - /data/invillia_app/vendor
    networks:
      - default
    depends_on:
      - db
    working_dir: /data/invillia_app/

  nginx:
    container_name: nginx_invillia_app
    image: nginx:1.16.0
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    links:
      - db

  db:
    image: mysql:5.7
    container_name: database_invillia_app
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invillia_app
    ports:
      - 3306:3306
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
